service: management-catalogues-unknownstatus

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 512MB
  timeout: 10
  role:
    Fn::ImportValue: management-${opt:stage,'dev'}-IamRoleLambdaExecution
  apiGateway:
    restApiId:
      Fn::ImportValue: management-${opt:stage,'dev'}-RestApiId
    restApiRootResourceId:
      Fn::ImportValue: management-${opt:stage,'dev'}-RootResourceId
# serverless-webpack configuration
# Enable auto-packing of external modules
custom:
  webpack:
    includeModules:
      # enable auto-packing of external modules
      packagePath: '../../package.json' 
plugins:
  #adding the plugin to be able to run offline emulation
  - serverless-offline 
  - serverless-webpack   
  - serverless-plugin-warmup
package:
  include:
  - /../../node_modules
functions:
  unknownstatus-create:
    warmup: true
    handler: UnknownStatusHandler.create
    events:
      - http:
          path: unknownstatus/
          method: post
          cors: true  
  unknownstatus-getAll:
    warmup: true
    handler: UnknownStatusHandler.getAll
    events:
      - http:
          path: unknownstatus/ 
          method: get
          cors: true
  unknownstatus-getOne:
    warmup: true
    handler: UnknownStatusHandler.getOne
    events:
      - http:
          path: unknownstatus/{id} 
          method: get
          cors: true          
  unknownstatus-Update:
    warmup: true
    handler: UnknownStatusHandler.update        
    events:
      - http:
          path: unknownstatus/{id} 
          method: put
          cors: true 