service: management-catalogues-agencies

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 512MB
  timeout: 10
  role:
    Fn::ImportValue: management-${opt:stage,'dev'}-IamRoleLambdaExecution 
  apiGateway:
    restApiId:
      Fn::ImportValue: management-${opt:stage,'dev'}-RestApiId
    restApiRootResourceId:
      Fn::ImportValue: management-${opt:stage,'dev'}-RootResourceId
# serverless-webpack configuration
# Enable auto-packing of external modules
custom:
  webpack:
    includeModules: 
      # enable auto-packing of external modules
      packagePath: '../../package.json' 
plugins:
  #adding the plugin to be able to run offline emulation
  - serverless-offline 
  - serverless-webpack
  - serverless-plugin-warmup
package:
  include:
  - /../../node_modules
functions:
  agency-create:
    warmup: true
    handler: AgencyHandler.create
    events:
      - http:
          path: agency/
          method: post
          cors: true
  agency-getAll:
    warmup: true
    handler: AgencyHandler.getAll
    events:
      - http:
          path: agency/ 
          method: get
          cors: true
  agency-getOne:
    warmup: true
    handler: AgencyHandler.getOne
    events:
      - http:
          path: agency/{id} 
          method: get
          cors: true                     
  agency-Update:
    warmup: true
    handler: AgencyHandler.update        
    events:
      - http:
          path: agency/{id} 
          method: put
          cors: true         
