service: management-catalogues-unknownstatus

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 512MB
  timeout: 10
  role:
    Fn::ImportValue: management-dev-IamRoleLambdaExecution
  apiGateway:
    restApiId:
      Fn::ImportValue: management-dev-RestApiId
    restApiRootResourceId:
      Fn::ImportValue: management-dev-RootResourceId
# serverless-webpack configuration
# Enable auto-packing of external modules
custom:
  webpack:
    includeModules: 
       packagePath: '../../package.json' # enable auto-packing of external modules
plugins:
  - serverless-offline #adding the plugin to be able to run offline emulation
  - serverless-webpack   
package:
  include:
  - ../../../node_modules
functions:
  unknownstatus-create:
    handler: UnknownStatusHandler.create
    events:
      - http:
          path: unknownstatus/
          method: post
          cors: true  
  unknownstatus-getAll:
    handler: UnknownStatusHandler.getAll
    events:
      - http:
          path: unknownstatus/ 
          method: get
          cors: true
  unknownstatus-getOne:
    handler: UnknownStatusHandler.getOne
    events:
      - http:
          path: unknownstatus/{id} 
          method: get
          cors: true          

  unknownstatus-Update:
    handler: UnknownStatusHandler.update        
    events:
      - http:
          path: unknownstatus/{id} 
          method: put
          cors: true 