service: management-catalogues-unknown

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 512MB
  timeout: 10
  role:
    Fn::ImportValue: management-dev-IamRoleLambdaExecution
  apiGateway:
    restApiId:
      Fn::ImportValue: management-dev-RestApiId
    restApiRootResourceId:
      Fn::ImportValue: management-dev-RootResourceId
# serverless-webpack configuration
# Enable auto-packing of external modules
custom:
  webpack:
    includeModules: 
       packagePath: '../../package.json' # enable auto-packing of external modules
plugins:
  - serverless-offline #adding the plugin to be able to run offline emulation
  - serverless-webpack   
package:
  include:
  - ../../../node_modules
functions:
  unknown-create:
    handler: UnknownHandler.create
    events:
      - http:
          path: unknown/
          method: post
          cors: true  
  unknown-getAll:
    handler: UnknownHandler.getAll
    events:
      - http:
          path: unknown/ 
          method: get
          cors: true
  unknown-getOne:
    handler: UnknownHandler.getOne
    events:
      - http:
          path: unknown/{id} 
          method: get
          cors: true            
  unknown-Update:
    handler: UnknownHandler.update        
    events:
      - http:
          path: unknown/{id} 
          method: put
          cors: true  