service: management-catalogues-subsidiaries

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 512MB
  timeout: 20
  role:
    Fn::ImportValue: management-${opt:stage,'dev'}-IamRoleLambdaExecution
  apiGateway:
    restApiId:
      Fn::ImportValue: management-${opt:stage,'dev'}-RestApiId
    restApiRootResourceId:
      Fn::ImportValue: management-${opt:stage,'dev'}-RootResourceId
# serverless-webpack configuration
# Enable auto-packing of external modules
custom:
  webpack:
   #Name of webpack configuration file
    webpackConfig: '../../webpack.config.js'    
  # Node modules configuration for packaging
    includeModules: 
  # enable auto-packing of external modules
      packagePath: '../../package.json' 
plugins:
  #adding the plugin to be able to run offline emulation
  - serverless-offline 
  - serverless-webpack
  - serverless-plugin-warmup
  - serverless-mocha-plugin  
package:
  include:
  - /../../node_modules
functions:
  subsidiary-create:
    warmup: true
    handler: CreateHandler.create
    events:
      - http:
          path: subsidiary/
          method: post
          cors: true
  subsidiary-getAll:
    warmup: true
    handler: GetAllHandler.getAll
    events:
      - http:
          path: subsidiary/
          method: get
          cors: true
  subsidiary-getOne:
    warmup: true
    handler: GetOneHandler.getOne
    events:
      - http:
          path: subsidiary/{id}
          method: get
          cors: true
  subsidiary-Update:
    warmup: true
    handler: UpdateHandler.update        
    events:
      - http:
          path: subsidiary/{id} 
          method: put
          cors: true         
  subsidiary-Delete:
    warmup: true
    handler: DeleteHandler.delete
    events:
      - http:
          path: subsidiary/{id}
          method: delete
          cors: true